name: Publish Dependencies

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  trigger:
    name: Build & Publish ${{ matrix.repo }}
    strategy:
      matrix:
        repo: [${{ vars.DEP_REPOS }}]
    
    runs-on: ubuntu-latest
  
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Publish
          token: ${{ secrets.XTATE_GITHUB_TOKEN }}
          repo: TSSArt/${{ matrix.repo }}
          ref: main
